---
# Filesystem and hardware modules prevented from loading
exorcism_blacklist_kernel_modules:
  - cramfs
  - freevxfs
  - hfs
  - hfsplus
  - jffs2
  - overlay
  - squashfs
  - udf
  - usb-storage
  - firewire-core

# Modules to leave loadable, removed from the list above
exorcism_blacklist_kernel_modules_exclude: []
