---
# Uncommon network protocol modules prevented from loading
exorcism_blacklist_network_modules:
  - atm
  - can
  - dccp
  - rds
  - sctp
  - tipc

# Modules to leave loadable, removed from the list above
exorcism_blacklist_network_modules_exclude: []
