---
# Packet forwarding. Hosts that route traffic need 1
exorcism_ipv4_ip_forward: 0
exorcism_ipv6_forwarding: 0

# Reverse path filtering. 1 is strict mode, 2 is loose
exorcism_rp_filter: 1

# Whether to accept IPv6 router advertisements
exorcism_ipv6_accept_ra: 0
