---
- name: 1.3.1.1 Ensure apparmor packages are installed
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
    state: present
  tags: 1.3_apparmor

- name: 1.3.1.4 Ensure apparmor_restrict_unprivileged_unconfined is enabled
  ansible.builtin.template:
    src: 90-apparmor.conf.j2
    dest: /etc/sysctl.d/90-apparmor.conf
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Reload sysctl
  tags: 1.3_apparmor
