---
- name: 1.6.1 Ensure /etc/motd is configured
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
    force: true
  tags: 1.6_banner

- name: 1.6.2 Ensure /etc/issue is configured
  ansible.builtin.template:
    src: banner.j2
    dest: /etc/issue
    owner: root
    group: root
    mode: "0644"
    force: true
  tags: 1.6_banner

- name: 1.6.3 Ensure /etc/issue.net is configured
  ansible.builtin.template:
    src: banner.j2
    dest: /etc/issue.net
    owner: root
    group: root
    mode: "0644"
    force: true
  tags: 1.6_banner
