---
- name: 3.3.X Network Configuration
  ansible.builtin.template:
    src: 90-net.conf.j2
    dest: /etc/sysctl.d/90-net.conf
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: Reload sysctl
  tags: 3.3_net
