---
- name: 4.4.1.1 Ensure iptables packages are installed
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present
  tags: 4.4_firewall

- name: 4.4.2.X Ensure iptables firewall rules are configured (IPv4)
  ansible.builtin.template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0600"
    force: true
  notify: Reload iptables
  tags: 4.4_firewall

- name: 4.4.2.X Ensure ip6tables firewall rules are configured (IPv6)
  ansible.builtin.template:
    src: rules.v6.j2
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: "0600"
    force: true
  notify: Reload iptables
  tags: 4.4_firewall
