# 5.3.3.2.1 Ensure password number of changed characters is configured
difok = 4
# 5.3.3.2.2 Ensure password length is configured
minlen = 15
# 5.3.3.2.3 Ensure password complexity is configured
minclass = 1
ucredit = -2
lcredit = -2
dcredit = -1
ocredit = -1
# 5.3.3.2.4 Ensure password same consecutive characters is configured
maxrepeat = 2
# 5.3.3.2.5 Ensure password maximum sequential characters is configured
maxsequence = 3
# 5.3.3.2.6 Ensure password dictionary check is enabled
dictcheck = 1
# 5.3.3.2.7 Ensure password quality checking is enforced
enforce_for_root = 1
# 5.3.3.2.8 Ensure password quality is enforced for the root user
